version: '3.8'

secrets:
  ConnectionStringsOptions__DefaultConnection:
    file: secrets/ConnectionStringsOptions__DefaultConnection
  JwtOptions__Audience:
    file: secrets/JwtOptions__Audience
  JwtOptions__Issuer:
    file: secrets/JwtOptions__Issuer
  JwtOptions__Key:
    file: secrets/JwtOptions__Key
  JwtOptions__Lifetime:
    file: secrets/JwtOptions__Lifetime
  ASPNETCORE_Kestrel__Certificates__Default__Path:
    file: secrets/ASPNETCORE_Kestrel__Certificates__Default__Path
  ASPNETCORE_Kestrel__Certificates__Default__Password:
    file: secrets/ASPNETCORE_Kestrel__Certificates__Default__Password

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    secrets:
      - ConnectionStringsOptions__DefaultConnection
      - JwtOptions__Audience
      - JwtOptions__Issuer
      - JwtOptions__Key
      - JwtOptions__Lifetime
      - ASPNETCORE_Kestrel__Certificates__Default__Path
      - ASPNETCORE_Kestrel__Certificates__Default__Password